<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_standard_userlocked_out_userproblem_use_5284cf</name>
   <tag></tag>
   <elementGuidId>a5d5ed5e-cfcc-42e1-b769-9b2d44366014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.bot_column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4db590f3-3936-437e-b6b9-27c8bc8898d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bot_column</value>
      <webElementGuid>5a8eb799-aacc-4bee-a945-6e211d07170b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/Login_Bot_graphic.png</value>
      <webElementGuid>db2c9f59-5821-496b-b64d-092e57236287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body&quot;]/div[@class=&quot;login_wrapper&quot;]/div[@class=&quot;login_wrapper-inner&quot;]/img[@class=&quot;bot_column&quot;]</value>
      <webElementGuid>8764a168-e454-44cc-846b-0525a45c20d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a70b694b-c695-49ec-b605-745ad236a8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'img/Login_Bot_graphic.png']</value>
      <webElementGuid>85420407-9943-4239-a80c-65655d84cf92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
